//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRC_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentDetail
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public Nullable<decimal> MarkObtained { get; set; }
        public Nullable<double> Percentage { get; set; }
    }
}
