//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRC_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        public int StudentID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ExamId { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> RollNumber { get; set; }
    }
}
